module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "adv-orange": "#fd990c",
        "adv-orange-dark": "#e6772e",
        "adv-navy": "#1a1a2e",
        "adv-red": "#d30000",
        "adv-cross": "#d32f2f",
        "adv-check": "#2e7d32",
        "adv-trustpilot": "#00b67a",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        "montserrat": ["Montserrat", "ui-sans-serif", "system-ui", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"],
        "alexandria": ["Alexandria", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "helvetica": ["Helvetica", "Arial", "ui-sans-serif", "system-ui", "sans-serif"],
        "pp_fragment": ["PP Fragment", "PP Fragment, Sans Regular", "ui-sans-serif", "system-ui", "sans-serif"],
        "pp_fragment_sans_regular": ["PP Fragment, Sans Regular", "ui-sans-serif", "system-ui", "sans-serif"],
        "poppins": ["Poppins", "ui-sans-serif", "system-ui", "sans-serif"],
        "montserrat": ["Montserrat", "ui-sans-serif", "system-ui", "sans-serif"],
        "roboto": ["Roboto", "ui-sans-serif", "system-ui", "sans-serif"],
        "work_sans": ["Work Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "retail_display": ["Retail Display", "ui-sans-serif", "system-ui", "sans-serif"],
        "dm_mono": ["DM Mono", "ui-monospace", "monospace"],
        "dm_sans": ["DM Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "times_new_roman": ["Times New Roman", "Times", "serif"],
        "proxima_nova": ["Proxima Nova", "Montserrat", "ui-sans-serif", "system-ui", "sans-serif"],
        "font_awesome_5_free": ["Font Awesome 5 Free", "sans-serif"],
        "apple_system": ["-apple-system", "BlinkMacSystemFont", "Segoe UI", "ui-sans-serif", "system-ui", "sans-serif"],
        "open_sans": ["Open Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "libre_franklin": ["Libre Franklin", "ui-sans-serif", "system-ui", "sans-serif"],
        "playfair_display": ["Playfair Display", "ui-serif", "Georgia", "serif"],
        "bitter": ["Bitter", "ui-serif", "Georgia", "serif"],
        "figtree": ["Figtree", "ui-sans-serif", "system-ui", "sans-serif"],
        "arial": ["Arial", "Helvetica", "ui-sans-serif", "system-ui", "sans-serif"],
        "ui_sans_serif": ["ui-sans-serif", "system-ui", "sans-serif"],
        "harmonia_sans_w01_regular": ["Harmonia Sans W01 Regular", "ui-sans-serif", "system-ui", "sans-serif"],
        "muli": ["Muli", "ui-sans-serif", "system-ui", "sans-serif"],
        "suisse_intl": ["Suisse Intl", "ui-sans-serif", "system-ui", "sans-serif"],
        "gilroy_bold": ["Gilroy-Bold", "ui-sans-serif", "system-ui", "sans-serif"],
        "gilroy_medium": ["Gilroy-Medium", "ui-sans-serif", "system-ui", "sans-serif"],
        "euclidcircularb": ["euclidCircularB", "ui-sans-serif", "system-ui", "sans-serif"],
        "georgia": ["Georgia", "ui-serif", "serif"],
        "times": ["Times New Roman", "Times", "ui-serif", "serif"]
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(21,128,61,0.5)" },
          "50%": { boxShadow: "0 0 0 10px rgba(21,128,61,0)" },
        },
        "slide-down": {
          "0%": { opacity: "0", transform: "translateY(-10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "bounce-subtle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-4px)" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "confetti-fall": {
          "0%": { transform: "translateY(-20px) rotate(var(--r))", opacity: "1" },
          "80%": { opacity: "1" },
          "100%": { transform: "translateY(280px) rotate(calc(var(--r) + 360deg))", opacity: "0" },
        },
        "result-pop": {
          "0%": { transform: "scale(0.6)", opacity: "0" },
          "70%": { transform: "scale(1.08)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-up": "fade-up 0.6s ease-out both",
        "fade-in": "fade-in 0.5s ease-out both",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "slide-down": "slide-down 0.4s ease-out both",
        "bounce-subtle": "bounce-subtle 2s ease-in-out infinite",
        "fade-in-up": "fade-in-up 0.6s ease-out both",
        "confetti-fall": "confetti-fall linear forwards",
        "result-pop": "result-pop 0.5s cubic-bezier(0.34,1.56,0.64,1) both",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
