export const MensHealthCurrencyWidget = () => {
  return (
    <div className="text-sm box-border caret-transparent inline leading-[14px] outline-[3px] font-harmonia_sans_w01_regular md:text-base md:leading-4">
      <div className="static text-base [align-items:normal] caret-black block leading-[normal] outline-0 z-auto right-auto top-auto md:fixed md:items-center md:aspect-auto md:caret-transparent md:hidden md:leading-4 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[2147483647] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:right-10 md:top-10">
        <div className="static text-black [align-items:normal] box-content caret-black block h-auto outline-0 text-start md:relative md:text-zinc-800 md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:h-10 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <select className="bg-white caret-black inline-block leading-[normal] outline-0 text-start visible pr-0 md:aspect-auto md:bg-zinc-100 md:caret-transparent md:hidden md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:invisible md:[mask-position:0%] md:bg-left-top md:pr-2.5 md:scroll-m-0 md:scroll-p-[auto]">
            <option
              value="USD"
              className="[align-items:normal] box-content caret-black gap-x-[normal] min-h-[19.2px] min-w-0 outline-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:min-h-6 md:min-w-6 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
            >
              US Dollar (USD)
            </option>
            <option
              value="EUR"
              className="[align-items:normal] box-content caret-black gap-x-[normal] min-h-[19.2px] min-w-0 outline-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:min-h-6 md:min-w-6 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
            >
              Euro (EUR)
            </option>
            <option
              value="GBP"
              className="[align-items:normal] box-content caret-black gap-x-[normal] min-h-[19.2px] min-w-0 outline-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:min-h-6 md:min-w-6 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
            >
              British Pound (GBP)
            </option>
            <option
              value="CAD"
              className="[align-items:normal] box-content caret-black gap-x-[normal] min-h-[19.2px] min-w-0 outline-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:min-h-6 md:min-w-6 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
            >
              Canadian Dollar (CAD)
            </option>
            <option
              value="AUD"
              className="[align-items:normal] box-content caret-black gap-x-[normal] min-h-[19.2px] min-w-0 outline-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:min-h-6 md:min-w-6 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
            >
              Australian Dollar (AUD)
            </option>
            <option
              value="AED"
              className="[align-items:normal] box-content caret-black gap-x-[normal] min-h-[19.2px] min-w-0 outline-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:min-h-6 md:min-w-6 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
            >
              United Arab Emirates Dirham (AED)
            </option>
            <option
              value="PHP"
              className="[align-items:normal] box-content caret-black gap-x-[normal] min-h-[19.2px] min-w-0 outline-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:min-h-6 md:min-w-6 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
            >
              Philippine Peso (PHP)
            </option>
          </select>
          <div className="static text-base [align-items:normal] bg-transparent shadow-none box-content caret-black block leading-[normal] outline-0 w-auto mx-0 rounded-none md:relative md:text-[15px] md:items-center md:aspect-auto md:bg-white md:shadow-[rgb(232,232,226)_4px_4px_9px_0px,rgb(232,232,226)_-4px_-4px_9px_0px] md:box-border md:caret-transparent md:flex md:leading-[15px] md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:mx-auto md:p-[7px] md:scroll-m-0 md:scroll-p-[auto] md:rounded-[5px] after:md:accent-auto after:md:items-center after:md:aspect-auto after:md:border-t-stone-700 after:md:box-border after:md:caret-transparent after:md:text-zinc-800 after:md:flex after:md:text-[15px] after:md:not-italic after:md:normal-nums after:md:font-normal after:md:tracking-[normal] after:md:leading-[15px] after:md:list-outside after:md:list-disc after:md:outline-[3px] after:md:overscroll-x-auto after:md:overscroll-y-auto after:md:pointer-events-auto after:md:relative after:md:snap-align-none after:md:snap-normal after:md:snap-none after:md:text-left after:md:no-underline after:md:decoration-auto after:md:indent-[0px] after:md:normal-case after:md:underline-offset-auto after:md:visible after:md:ml-auto after:md:my-auto after:md:scroll-m-0 after:md:scroll-p-[auto] after:md:rounded-[3px] after:md:border-b-transparent after:md:border-x-transparent after:md:border-separate after:md:border-[6px] after:md:border-solid after:md:right-0 after:md:top-[5px] after:md:font-harmonia_sans_w01_regular">
            <div className="box-content caret-black outline-0 md:aspect-auto md:box-border md:caret-transparent md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
              <div className="bg-none bg-repeat bg-auto box-content caret-black block h-auto outline-0 align-baseline w-auto mr-0 rounded-none md:aspect-auto md:bg-[url('https://cdn.shopify.com/s/files/1/0194/1736/6592/t/1/assets/ba-flags.png?=14261939516959647149')] md:bg-no-repeat md:bg-size-[30px] md:box-border md:caret-transparent md:inline-block md:h-5 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-middle md:w-[30px] md:[mask-position:0%] md:bg-[position:0px_-3960px] md:mr-1.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-bl md:rounded-br md:rounded-tl md:rounded-tr"></div>
            </div>
            <span className="text-base box-content caret-black inline leading-[normal] outline-0 mx-0 md:text-sm md:aspect-auto md:box-border md:caret-transparent md:block md:leading-[14px] md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mx-[7px] md:scroll-m-0 md:scroll-p-[auto]">
              USD
            </span>
          </div>
          <ul className="static bg-transparent shadow-none box-content caret-black block list-disc max-h-none max-w-none outline-0 overflow-x-visible overflow-y-visible w-auto z-auto my-0 pl-10 rounded-none right-auto top-auto md:absolute md:aspect-auto md:bg-white md:shadow-[rgba(0,0,0,0.15)_0px_0px_16px_-5px] md:box-border md:caret-transparent md:hidden md:list-none md:max-h-[302px] md:max-w-[266px] md:outline-[3px] md:overflow-x-hidden md:overflow-y-auto md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-max md:z-[999999999] md:[mask-position:0%] md:bg-left-top md:my-2 md:pl-0 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[7px] md:right-0 md:top-full">
            <li className="box-content caret-black outline-0 text-wrap w-auto p-0 border-t-0 border-black md:aspect-auto md:border-b-zinc-900/10 md:border-l-zinc-900/10 md:border-r-zinc-900/10 md:border-t-neutral-300/40 md:box-border md:caret-transparent md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-full md:[mask-position:0%] md:bg-left-top md:px-3.5 md:py-[13px] md:scroll-m-0 md:scroll-p-[auto] md:border-t md:border-solid">
              <div className="box-content caret-black block outline-0 text-wrap md:aspect-auto md:box-border md:caret-transparent md:inline-block md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="bg-none bg-repeat bg-auto box-content caret-black block h-auto outline-0 text-wrap align-baseline w-auto mr-0 rounded-none md:aspect-auto md:bg-[url('https://cdn.shopify.com/s/files/1/0194/1736/6592/t/1/assets/ba-flags.png?=14261939516959647149')] md:bg-no-repeat md:bg-size-[30px] md:box-border md:caret-transparent md:inline-block md:h-5 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:align-middle md:w-[30px] md:[mask-position:0%] md:bg-[position:0px_-3960px] md:mr-1.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-bl md:rounded-br md:rounded-tl md:rounded-tr"></div>
              </div>
              <span className="text-base box-content caret-black leading-[normal] outline-0 text-wrap mx-0 md:text-sm md:aspect-auto md:box-border md:caret-transparent md:leading-[14px] md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:mx-[7px] md:scroll-m-0 md:scroll-p-[auto]">
                US Dollar (USD)
              </span>
            </li>
            <li className="box-content caret-black outline-0 text-wrap w-auto p-0 border-t-0 border-black md:aspect-auto md:border-b-zinc-900/10 md:border-l-zinc-900/10 md:border-r-zinc-900/10 md:border-t-neutral-300/40 md:box-border md:caret-transparent md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-full md:[mask-position:0%] md:bg-left-top md:px-3.5 md:py-[13px] md:scroll-m-0 md:scroll-p-[auto] md:border-t md:border-solid">
              <div className="box-content caret-black block outline-0 text-wrap md:aspect-auto md:box-border md:caret-transparent md:inline-block md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="bg-none bg-repeat bg-auto box-content caret-black block h-auto outline-0 text-wrap align-baseline w-auto mr-0 rounded-none md:aspect-auto md:bg-[url('https://cdn.shopify.com/s/files/1/0194/1736/6592/t/1/assets/ba-flags.png?=14261939516959647149')] md:bg-no-repeat md:bg-size-[30px] md:box-border md:caret-transparent md:inline-block md:h-5 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:align-middle md:w-[30px] md:[mask-position:0%] md:bg-[position:0px_-1220px] md:mr-1.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-bl md:rounded-br md:rounded-tl md:rounded-tr"></div>
              </div>
              <span className="text-base box-content caret-black leading-[normal] outline-0 text-wrap mx-0 md:text-sm md:aspect-auto md:box-border md:caret-transparent md:leading-[14px] md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:mx-[7px] md:scroll-m-0 md:scroll-p-[auto]">
                Euro (EUR)
              </span>
            </li>
            <li className="box-content caret-black outline-0 text-wrap w-auto p-0 border-t-0 border-black md:aspect-auto md:border-b-zinc-900/10 md:border-l-zinc-900/10 md:border-r-zinc-900/10 md:border-t-neutral-300/40 md:box-border md:caret-transparent md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-full md:[mask-position:0%] md:bg-left-top md:px-3.5 md:py-[13px] md:scroll-m-0 md:scroll-p-[auto] md:border-t md:border-solid">
              <div className="box-content caret-black block outline-0 text-wrap md:aspect-auto md:box-border md:caret-transparent md:inline-block md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="bg-none bg-repeat bg-auto box-content caret-black block h-auto outline-0 text-wrap align-baseline w-auto mr-0 rounded-none md:aspect-auto md:bg-[url('https://cdn.shopify.com/s/files/1/0194/1736/6592/t/1/assets/ba-flags.png?=14261939516959647149')] md:bg-no-repeat md:bg-size-[30px] md:box-border md:caret-transparent md:inline-block md:h-5 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:align-middle md:w-[30px] md:[mask-position:0%] md:bg-[position:0px_-1360px] md:mr-1.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-bl md:rounded-br md:rounded-tl md:rounded-tr"></div>
              </div>
              <span className="text-base box-content caret-black leading-[normal] outline-0 text-wrap mx-0 md:text-sm md:aspect-auto md:box-border md:caret-transparent md:leading-[14px] md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:mx-[7px] md:scroll-m-0 md:scroll-p-[auto]">
                British Pound (GBP)
              </span>
            </li>
            <li className="box-content caret-black outline-0 text-wrap w-auto p-0 border-t-0 border-black md:aspect-auto md:border-b-zinc-900/10 md:border-l-zinc-900/10 md:border-r-zinc-900/10 md:border-t-neutral-300/40 md:box-border md:caret-transparent md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-full md:[mask-position:0%] md:bg-left-top md:px-3.5 md:py-[13px] md:scroll-m-0 md:scroll-p-[auto] md:border-t md:border-solid">
              <div className="box-content caret-black block outline-0 text-wrap md:aspect-auto md:box-border md:caret-transparent md:inline-block md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="bg-none bg-repeat bg-auto box-content caret-black block h-auto outline-0 text-wrap align-baseline w-auto mr-0 rounded-none md:aspect-auto md:bg-[url('https://cdn.shopify.com/s/files/1/0194/1736/6592/t/1/assets/ba-flags.png?=14261939516959647149')] md:bg-no-repeat md:bg-size-[30px] md:box-border md:caret-transparent md:inline-block md:h-5 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:align-middle md:w-[30px] md:[mask-position:0%] md:bg-[position:0px_-660px] md:mr-1.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-bl md:rounded-br md:rounded-tl md:rounded-tr"></div>
              </div>
              <span className="text-base box-content caret-black leading-[normal] outline-0 text-wrap mx-0 md:text-sm md:aspect-auto md:box-border md:caret-transparent md:leading-[14px] md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:mx-[7px] md:scroll-m-0 md:scroll-p-[auto]">
                Canadian Dollar (CAD)
              </span>
            </li>
            <li className="box-content caret-black outline-0 text-wrap w-auto p-0 border-t-0 border-black md:aspect-auto md:border-b-zinc-900/10 md:border-l-zinc-900/10 md:border-r-zinc-900/10 md:border-t-neutral-300/40 md:box-border md:caret-transparent md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-full md:[mask-position:0%] md:bg-left-top md:px-3.5 md:py-[13px] md:scroll-m-0 md:scroll-p-[auto] md:border-t md:border-solid">
              <div className="box-content caret-black block outline-0 text-wrap md:aspect-auto md:box-border md:caret-transparent md:inline-block md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="bg-none bg-repeat bg-auto box-content caret-black block h-auto outline-0 text-wrap align-baseline w-auto mr-0 rounded-none md:aspect-auto md:bg-[url('https://cdn.shopify.com/s/files/1/0194/1736/6592/t/1/assets/ba-flags.png?=14261939516959647149')] md:bg-no-repeat md:bg-size-[30px] md:box-border md:caret-transparent md:inline-block md:h-5 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:align-middle md:w-[30px] md:[mask-position:0%] md:bg-[position:0px_-240px] md:mr-1.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-bl md:rounded-br md:rounded-tl md:rounded-tr"></div>
              </div>
              <span className="text-base box-content caret-black leading-[normal] outline-0 text-wrap mx-0 md:text-sm md:aspect-auto md:box-border md:caret-transparent md:leading-[14px] md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:mx-[7px] md:scroll-m-0 md:scroll-p-[auto]">
                Australian Dollar (AUD)
              </span>
            </li>
            <li className="box-content caret-black outline-0 text-wrap w-auto p-0 border-t-0 border-black md:aspect-auto md:border-b-zinc-900/10 md:border-l-zinc-900/10 md:border-r-zinc-900/10 md:border-t-neutral-300/40 md:box-border md:caret-transparent md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-full md:[mask-position:0%] md:bg-left-top md:px-3.5 md:py-[13px] md:scroll-m-0 md:scroll-p-[auto] md:border-t md:border-solid">
              <div className="box-content caret-black block outline-0 text-wrap md:aspect-auto md:box-border md:caret-transparent md:inline-block md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="bg-none bg-repeat bg-auto box-content caret-black block h-auto outline-0 text-wrap align-baseline w-auto mr-0 rounded-none md:aspect-auto md:bg-[url('https://cdn.shopify.com/s/files/1/0194/1736/6592/t/1/assets/ba-flags.png?=14261939516959647149')] md:bg-no-repeat md:bg-size-[30px] md:box-border md:caret-transparent md:inline-block md:h-5 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:align-middle md:w-[30px] md:[mask-position:0%] md:bg-[position:0px_-3060px] md:mr-1.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-bl md:rounded-br md:rounded-tl md:rounded-tr"></div>
              </div>
              <span className="text-base box-content caret-black leading-[normal] outline-0 text-wrap mx-0 md:text-sm md:aspect-auto md:box-border md:caret-transparent md:leading-[14px] md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:mx-[7px] md:scroll-m-0 md:scroll-p-[auto]">
                United Arab Emirates Dirham (AED)
              </span>
            </li>
            <li className="box-content caret-black outline-0 text-wrap w-auto p-0 border-t-0 border-black md:aspect-auto md:border-b-zinc-900/10 md:border-l-zinc-900/10 md:border-r-zinc-900/10 md:border-t-neutral-300/40 md:box-border md:caret-transparent md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-full md:[mask-position:0%] md:bg-left-top md:px-3.5 md:py-[13px] md:scroll-m-0 md:scroll-p-[auto] md:border-t md:border-solid">
              <div className="box-content caret-black block outline-0 text-wrap md:aspect-auto md:box-border md:caret-transparent md:inline-block md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="bg-none bg-repeat bg-auto box-content caret-black block h-auto outline-0 text-wrap align-baseline w-auto mr-0 rounded-none md:aspect-auto md:bg-[url('https://cdn.shopify.com/s/files/1/0194/1736/6592/t/1/assets/ba-flags.png?=14261939516959647149')] md:bg-no-repeat md:bg-size-[30px] md:box-border md:caret-transparent md:inline-block md:h-5 md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:align-middle md:w-[30px] md:[mask-position:0%] md:bg-[position:0px_-40px] md:mr-1.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-bl md:rounded-br md:rounded-tl md:rounded-tr"></div>
              </div>
              <span className="text-base box-content caret-black leading-[normal] outline-0 text-wrap mx-0 md:text-sm md:aspect-auto md:box-border md:caret-transparent md:leading-[14px] md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:mx-[7px] md:scroll-m-0 md:scroll-p-[auto]">
                Philippine Peso (PHP)
              </span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
};
