export const AbcNewsNavbarMenuButton = () => {
  return (
    <div className="[align-items:normal] box-content caret-black block min-h-0 min-w-0 outline-0 md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:min-h-[auto] md:min-w-[auto] md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
      <div
        aria-label="Site Menu"
        role="button"
        className="static box-content caret-black block h-auto justify-normal leading-[normal] min-h-0 min-w-0 outline-0 mr-0 rounded-none md:relative md:aspect-auto md:box-border md:caret-transparent md:flex md:h-10 md:justify-center md:leading-[0px] md:min-h-[auto] md:min-w-[auto] md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mr-4 md:p-[11px] md:scroll-m-0 md:scroll-p-[auto] md:rounded-[80px]"
      >
        <div className="static bg-transparent box-content caret-black h-auto min-h-0 min-w-0 outline-0 w-auto my-0 rounded-none md:relative md:aspect-auto md:bg-black md:box-border md:caret-transparent md:h-0.5 md:min-h-[auto] md:min-w-[auto] md:outline-[3px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-5 md:[mask-position:0%] md:bg-left-top md:my-2 md:scroll-m-0 md:scroll-p-[auto] md:rounded-bl md:rounded-br md:rounded-tl md:rounded-tr before:md:accent-auto before:md:aspect-auto before:md:bg-black before:md:box-border before:md:caret-transparent before:md:text-black before:md:block before:md:text-base before:md:not-italic before:md:normal-nums before:md:font-normal before:md:h-0.5 before:md:tracking-[normal] before:md:leading-[0px] before:md:list-outside before:md:list-disc before:md:outline-[3px] before:md:overscroll-x-auto before:md:overscroll-y-auto before:md:pointer-events-auto before:md:absolute before:md:snap-align-none before:md:snap-normal before:md:snap-none before:md:text-start before:md:no-underline before:md:decoration-auto before:md:indent-[0px] before:md:normal-case before:md:underline-offset-auto before:md:visible before:md:w-5 before:md:scroll-m-0 before:md:scroll-p-[auto] before:md:rounded-bl before:md:rounded-br before:md:rounded-tl before:md:rounded-tr before:md:border-separate before:md:left-0 before:md:bottom-[7px] before:md:font-sansseriffont after:md:accent-auto after:md:aspect-auto after:md:bg-black after:md:box-border after:md:caret-transparent after:md:text-black after:md:block after:md:text-base after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-0.5 after:md:tracking-[normal] after:md:leading-[0px] after:md:list-outside after:md:list-disc after:md:outline-[3px] after:md:overscroll-x-auto after:md:overscroll-y-auto after:md:pointer-events-auto after:md:absolute after:md:snap-align-none after:md:snap-normal after:md:snap-none after:md:text-start after:md:no-underline after:md:decoration-auto after:md:indent-[0px] after:md:normal-case after:md:underline-offset-auto after:md:visible after:md:w-5 after:md:scroll-m-0 after:md:scroll-p-[auto] after:md:rounded-bl after:md:rounded-br after:md:rounded-tl after:md:rounded-tr after:md:border-separate after:md:left-0 after:md:top-[7px] after:md:font-sansseriffont"></div>
      </div>
    </div>
  );
};
